version: "2"

services:
  web:
    build: .
    container_name: api_web
    ports:
      - "8003:3000"
    restart: always

  nginx:
    build: ./nginx
    container_name: api_nginx
    ports:
      - "3000:3000"
    restart: always
